### PR TITLE
Pin to released versions of spotlight and indexing dependencies

### PR DESCRIPTION
**Pull request by cbeer**
Connects to sul-dlss/spotlight#1204

### CODE REVIEW

**Comment by ndushay** [comment]
do you have any ideas to keep transparency on which version of spotlight-dor-resources is in use?

**Comment by cbeer** [comment]
Once we get the rest of the SALT indexing in, maybe it's finally time to cut a release for that? I would do it now, but it seems like it's still in a state of flux..

**Comment by ndushay** [comment]
maybe make a separate issue for it, indicating dependencies???  Or just wait until tomorrow?  (I'm codin' as fast as I can, captain!)

**Comment by ndushay** [comment]
Can you add a comment in the gemfile as to why, so it's at least documented?  and what we're waiting for?

**Comment by cbeer** [comment]
Can you suggest a reasonable comment? I don't think there's any sul-exhibits-template-specific reason we're pulling from git, there just isn't a release for the gem yet.

**Comment by ndushay** [comment]
# waiting for stability and/or feigenbaum indexing needs, hopefully by 2015-11 or sooner

how's that?

**Comment by ndushay** [comment]
needs a rebase, then I'll merge.

**Comment by cbeer** [comment]
Rebased.

**Comment by ndushay** [comment]
Let's talk about this at standup.  The more I think about it, the more I'm inclined to just release the gems as often as we need to, with the minor or patch releases increasing.

**Comment by ndushay** [comment]
waiting for release of spotlight-dor-resources gem.

**Comment by ndushay** [comment]
@cbeer @peetucket   this is ready.  Sorry about the hound noise - I forgot to add the magic to rubocop.yml (but fixed it later)

**Pull request merged**
